changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes ⚠️
      labels:
        - "breaking change"
    - title: Bug Fixes 🐛
      labels:
          - "bug"
    - title: Features 🎉
      labels:
        - "enhancement"
    - title: Dependency Updates ⬆️
      labels:
        - "dependencies"
    - title: Other Changes
      labels:
        - "*"