# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@2.0.3

jobs:
  publish:
    executor:
      name: python/default
      tag: 3.10.4
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Build and publish to PyPi
          command: poetry publish --build --no-interaction --username $PYPI_USERNAME --password $PYPI_PASSWORD

workflows:
  publish:
    jobs:
      - publish:
          context:
            - PyPi
          filters:
            branches:
              only: main # only deploy when on main
